"""new columns (exchange and short name of exchange) in Company models

Revision ID: a9052aa6b235
Revises: b8d1e557d115
Create Date: 2020-08-01 10:51:55.084778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9052aa6b235'
down_revision = 'b8d1e557d115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('exchange', sa.String(), nullable=True))
    op.add_column('company', sa.Column('exchangeShortName', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'exchangeShortName')
    op.drop_column('company', 'exchange')
    # ### end Alembic commands ###
