"""empty message

Revision ID: b8d1e557d115
Revises: 837b5ef18ef2
Create Date: 2020-07-11 20:18:57.079831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8d1e557d115'
down_revision = '837b5ef18ef2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('description', sa.Text(), nullable=True))
    op.drop_column('company', 'decription')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('decription', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('company', 'description')
    # ### end Alembic commands ###
