"""datatype and name of column 'date' in 'company_key_metrics' table was changed from datetime to date

Revision ID: c75e406ff4d0
Revises: 8d7cde0e15db
Create Date: 2021-04-27 00:39:49.720932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c75e406ff4d0'
down_revision = '8d7cde0e15db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_key_metrics', sa.Column('metrics_date', sa.Date(), nullable=True))
    op.drop_column('company_key_metrics', 'date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_key_metrics', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('company_key_metrics', 'metrics_date')
    # ### end Alembic commands ###
