from sid.db import db

class Company_key_metrics(db.Model):
    """the model to describe key metrics of some company"""
    id = db.Column(db.Integer, primary_key=True)
    company_id = db.Column(db.Integer, db.ForeignKey('company.id'), nullable=False)
    date = db.Column(db.DateTime, nullable=False)
    revenue_per_share = db.Column(db.Numeric, nullable = True)
    net_income_per_share = db.Column(db.Numeric, nullable = True)
    operating_cash_flow_per_share = db.Column(db.Numeric, nullable = True)
    free_cash_flow_per_share = db.Column(db.Numeric, nullable = True)
    cash_per_share = db.Column(db.Numeric, nullable = True)
    book_value_per_share = db.Column(db.Numeric, nullable = True)
    tangible_book_value_per_share = db.Column(db.Numeric, nullable = True)
    shareholders_equity_per_share = db.Column(db.Numeric, nullable = True)
    interest_debt_per_share = db.Column(db.Numeric, nullable = True)
    market_cap = db.Column(db.Numeric, nullable = True)
    enterprise_value = db.Column(db.Numeric, nullable = True)
    pe_ratio = db.Column(db.Numeric, nullable = True)
    price_to_sales_ratio = db.Column(db.Numeric, nullable = True)
    pocfratio = db.Column(db.Numeric, nullable = True)
    pfcf_ratio = db.Column(db.Numeric, nullable = True)
    pb_ratio = db.Column(db.Numeric, nullable = True)
    ptb_ratio = db.Column(db.Numeric, nullable = True)
    ev_to_sales = db.Column(db.Numeric, nullable = True)
    enterprise_value_over_ebitda = db.Column(db.Numeric, nullable = True)
    ev_to_operating_cash_flow = db.Column(db.Numeric, nullable = True)
    ev_to_free_cash_flow = db.Column(db.Numeric, nullable = True)
    earnings_yield = db.Column(db.Numeric, nullable = True)
    free_cash_flow_yield = db.Column(db.Numeric, nullable = True)
    debt_to_equity = db.Column(db.Numeric, nullable = True)
    debt_to_assets = db.Column(db.Numeric, nullable = True)
    net_debt_to_ebitda = db.Column(db.Numeric, nullable = True)
    current_ratio = db.Column(db.Numeric, nullable = True)
    interest_coverage = db.Column(db.Numeric, nullable = True)
    income_quality = db.Column(db.Numeric, nullable = True)
    dividend_yield = db.Column(db.Numeric, nullable = True)
    payout_ratio = db.Column(db.Numeric, nullable = True)
    sales_general_and_administrative_to_revenue = db.Column(db.Numeric, nullable = True)
    research_and_developement_to_revenue = db.Column(db.Numeric, nullable = True)
    intangibles_to_total_assets = db.Column(db.Numeric, nullable = True)
    capex_to_operating_cash_flow = db.Column(db.Numeric, nullable = True)
    capex_to_revenue = db.Column(db.Numeric, nullable = True)
    capex_to_depreciation = db.Column(db.Numeric, nullable = True)
    stock_based_compensation_to_revenue = db.Column(db.Numeric, nullable = True)
    graham_number = db.Column(db.Numeric, nullable = True)
    roic = db.Column(db.Numeric, nullable = True)
    return_on_tangible_assets = db.Column(db.Numeric, nullable = True)
    graham_net_net = db.Column(db.Numeric, nullable = True)
    working_capital = db.Column(db.Numeric, nullable = True)
    tangible_asset_value = db.Column(db.Numeric, nullable = True)
    net_current_asset_value = db.Column(db.Numeric, nullable = True)
    invested_capital = db.Column(db.Numeric, nullable = True)
    average_receivables = db.Column(db.Numeric, nullable = True)
    average_payables = db.Column(db.Numeric, nullable = True)
    average_inventory = db.Column(db.Numeric, nullable = True)
    days_sales_outstanding = db.Column(db.Numeric, nullable = True)
    days_payables_outstanding = db.Column(db.Numeric, nullable = True)
    days_of_inventory_on_hand = db.Column(db.Numeric, nullable = True)
    receivables_turnover = db.Column(db.Numeric, nullable = True)
    payables_turnover = db.Column(db.Numeric, nullable = True)
    inventory_turnover = db.Column(db.Numeric, nullable = True)
    roe = db.Column(db.Numeric, nullable = True)
    capex_per_share = db.Column(db.Numeric, nullable = True)

    def __repr__(self):
        return f'Company key metrics {self.company_id}'